### PR TITLE
Feature/trigger and swap attributes

### PR DESCRIPTION
**Pull request by wimdeblauwe**

### CODE REVIEW

**Review by checketts — APPROVED** [review]
Let's add a test describing the behavior you demonstrated with the th:with / lastRow idea.

**Comment by wimdeblauwe** [comment]
Tests added. I also added a test for `th:each` to make that works as well.

**Comment by wimdeblauwe** [comment]
@checketts Tests ok like this or did you have something else in mind?

**Comment by checketts** [comment]
Those look great! Thanks

**Pull request merged**
